# Generated by Django 5.1 on 2024-08-15 17:58

import datetime
import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='logo',
            field=models.ImageField(null=True, upload_to=games.models.logo_directory_path, verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='logo',
            field=models.ImageField(null=True, upload_to=games.models.logo_directory_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.ManyToManyField(null=True, to='games.developer', verbose_name='developer'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_platform',
            field=models.ManyToManyField(null=True, to='games.gameplatform'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.ManyToManyField(null=True, to='games.publisher', verbose_name='publisher'),
        ),
        migrations.AlterField(
            model_name='game',
            name='release',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Release game'),
        ),
        migrations.AlterField(
            model_name='gamesimages',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='gamesimages',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='description',
            field=models.TextField(null=True, verbose_name='Descriptions'),
        ),
    ]
