# Generated by Django 5.1 on 2024-09-12 09:43

import django.db.models.deletion
import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='developer',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='game',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='game',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gamesimages',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gamesimages',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='genres',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='genres',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='genres',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='genres',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Descriptions'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Descriptions'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(null=True, to='games.genres', verbose_name='genres'),
        ),
        migrations.AlterField(
            model_name='game',
            name='poster',
            field=models.ImageField(null=True, upload_to=games.models.game_poster_directory_path, verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.review', verbose_name='Parent'),
        ),
    ]
